#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
#define int long long
using namespace std;

const int MOD = 998244353;
int64_t solve(int N, int M, int K) {
  vector<vector<int>> f(N + 1, vector<int> (K + 1, 0));
  for (int i = 1; i <= K; i++) {
    if (i <= M) f[1][i] = 1;
  }
  for (int i = 2; i <= N; i++) {
    for (int j = 1; j <= K; j++) {
      for (int k = 1; k <= min(M, j); k++) {
        f[i][j] += f[i - 1][j - k]; 
        f[i][j] %= MOD;
      }
    }
  }
  int ans = 0;
  for (int i = 1; i <= K; i++) 
    ans = (ans + f[N][i]) % MOD;
  return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
signed main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N, M, K;
    std::cin >> N >> M >> K;
    auto ans = solve(N, M, K);
    std::cout << ans << '\n';
    return 0;
}
