#!/usr/bin/env python3
# from typing import *

YES = 'YES'
NO = 'NO'

# def solve(testcases: int, a: List[int]) -> List[str]:
def solve(testcases, a):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    testcases = int(input())
    a = [None for _ in range(testcases)]
    for i in range(testcases):
        a[i] = int(input())
    b = solve(testcases, a)
    for i in range(testcases):
        print(b[i])

if __name__ == '__main__':
    main()
