#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = random.randint(1, 100)
    a = random.randint(1, 20)
    b = random.randint(1, 20)
    x = random.randint(1, 20)
    y = random.randint(1, 20)
    z = random.randint(1, 20)
    print(n, a, b, x, y, z)

if __name__ == "__main__":
    t = 100
    print(t)
    for i in range(t):
        main()
